include ../constants.mk

MODULES=\
	type_pkg \
	tools_pkg \
	instr_imm_decoder \
	instr_reg_decoder \
	instr_ctrl_decoder \
	instr_decoder \
	sgnext12 \
	sgnext20 \
	sgnext \
	controller \
	regfile \
	imem \
	imem_test
	#riscv
TESTS=\
	regfile
	#riscv

include ../rules.mk
