include ../constants.mk

MODULES=\
	type_pkg \
	instr_imm_decoder \
	instr_reg_decoder \
	instr_ctrl_decoder \
	instr_misc_decoder \
	sgnext12 \
	sgnext20 \
	sgnext \
	controller
#TESTS=

include ../rules.mk
